from spatial_egt.data_processing.spatial_statistics.custom import (
    nc_dist,
    proportion_cell,
    spatial_subsample_dist,
)
from spatial_egt.data_processing.spatial_statistics.muspan_statistics import (
    anni,
    cpcf,
    cross_k,
    entropy,
    global_moransi,
    kl_divergence,
    local_moransi_dist,
    nn_dist,
    qcm,
    wasserstein,
)

STATISTIC_REGISTRY = {
    # Custom
    "NC_Resistant": nc_dist,
    "NC_Sensitive": nc_dist,
    "Proportion_Sensitive": proportion_cell,
    "Spatial_Subsample": spatial_subsample_dist,
    # MuSpAn
    "ANNI_Resistant": anni,
    "ANNI_Sensitive": anni,
    "CPCF_Resistant": cpcf,
    "CPCF_Sensitive": cpcf,
    "Cross_Ripleys_k_Resistant": cross_k,
    "Cross_Ripleys_k_Sensitive": cross_k,
    "Entropy": entropy,
    "Global_Morans_i_Resistant": global_moransi,
    "Global_Morans_i_Sensitive": global_moransi,
    "KL_Divergence": kl_divergence,
    "Local_Morans_i_Resistant": local_moransi_dist,
    "Local_Morans_i_Sensitive": local_moransi_dist,
    "NN_Resistant": nn_dist,
    "NN_Sensitive": nn_dist,
    "SES": qcm,
    "Wasserstein": wasserstein,
}

STATISTIC_PARAMS = {
    "in_silico": {
        "NC_Resistant": {"radius": 3, "return_fs": True},
        "NC_Sensitive": {"radius": 3, "return_fs": False},
        "Proportion_Sensitive": {"cell_type": "sensitive"},
        "Spatial_Subsample": {"sample_length": 5},
        "ANNI_Resistant": {"cell_type1": "resistant", "cell_type2": "sensitive"},
        "ANNI_Sensitive": {"cell_type1": "sensitive", "cell_type2": "resistant"},
        "CPCF_Resistant": {
            "max_radius": 5,
            "annulus_step": 1,
            "annulus_width": 3,
            "cell_type1": "resistant",
            "cell_type2": "sensitive",
        },
        "CPCF_Sensitive": {
            "max_radius": 5,
            "annulus_step": 1,
            "annulus_width": 3,
            "cell_type1": "sensitive",
            "cell_type2": "resistant",
        },
        "Cross_Ripleys_k_Resistant": {
            "max_radius": 6,
            "step": 1,
            "cell_type1": "resistant",
            "cell_type2": "sensitive",
        },
        "Cross_Ripleys_k_Sensitive": {
            "max_radius": 6,
            "step": 1,
            "cell_type1": "sensitive",
            "cell_type2": "resistant",
        },
        "Global_Morans_i_Resistant": {"cell_type": "resistant", "side_length": 5},
        "Global_Morans_i_Sensitive": {"cell_type": "sensitive", "side_length": 5},
        "KL_Divergence": {"mesh_step": 3},
        "Local_Morans_i_Resistant": {"cell_type": "resistant", "side_length": 5},
        "Local_Morans_i_Sensitive": {"cell_type": "sensitive", "side_length": 5},
        "NN_Resistant": {"cell_type1": "resistant", "cell_type2": "sensitive"},
        "NN_Sensitive": {"cell_type1": "sensitive", "cell_type2": "resistant"},
        "SES": {"side_length": 10},
    },
    "in_vitro": {
        "NC_Resistant": {"radius": 50, "return_fs": True},
        "NC_Sensitive": {"radius": 50, "return_fs": False},
        "Proportion_Sensitive": {"cell_type": "sensitive"},
        "Spatial_Subsample": {"sample_length": 50},
        "ANNI_Resistant": {"cell_type1": "resistant", "cell_type2": "sensitive"},
        "ANNI_Sensitive": {"cell_type1": "sensitive", "cell_type2": "resistant"},
        "Cross_Ripleys_k_Resistant": {
            "max_radius": 100,
            "step": 10,
            "cell_type1": "resistant",
            "cell_type2": "sensitive",
        },
        "Cross_Ripleys_k_Sensitive": {
            "max_radius": 100,
            "step": 10,
            "cell_type1": "sensitive",
            "cell_type2": "resistant",
        },
        "CPCF_Resistant": {
            "max_radius": 100,
            "annulus_step": 10,
            "annulus_width": 10,
            "cell_type1": "resistant",
            "cell_type2": "sensitive",
        },
        "CPCF_Sensitive": {
            "max_radius": 100,
            "annulus_step": 10,
            "annulus_width": 10,
            "cell_type1": "sensitive",
            "cell_type2": "resistant",
        },
        "Global_Morans_i_Resistant": {"cell_type": "resistant", "side_length": 50},
        "Global_Morans_i_Sensitive": {"cell_type": "sensitive", "side_length": 50},
        "KL_Divergence": {"mesh_step": 100},
        "Local_Morans_i_Resistant": {"cell_type": "resistant", "side_length": 50},
        "Local_Morans_i_Sensitive": {"cell_type": "sensitive", "side_length": 50},
        "NN_Resistant": {"cell_type1": "resistant", "cell_type2": "sensitive"},
        "NN_Sensitive": {"cell_type1": "sensitive", "cell_type2": "resistant"},
        "SES": {"side_length": 100},
    },
}
