from spatial_egt.data_processing.spatial_statistics.custom import (
    nc_dist,
    proportion_cell,
    spatial_subsample_dist,
)
from spatial_egt.data_processing.spatial_statistics.muspan_statistics import (
    anni,
    cpcf,
    cross_k,
    entropy,
    global_moransi,
    kl_divergence,
    local_moransi_dist,
    nn_dist,
    qcm,
    wasserstein,
)

STATISTIC_REGISTRY = {
    # Custom
    "NC_RS": nc_dist,
    "NC_SR": nc_dist,
    "Proportion_Sensitive": proportion_cell,
    "Spatial_Subsample": spatial_subsample_dist,
    # MuSpAn
    "ANNI_RS": anni,
    "ANNI_SR": anni,
    "CPCF_RR": cpcf,
    "CPCF_RS": cpcf,
    "CPCF_SR": cpcf,
    "CPCF_SS": cpcf,
    "Ripleys_k_RR": cross_k,
    "Ripleys_k_RS": cross_k,
    "Ripleys_k_SR": cross_k,
    "Ripleys_k_SS": cross_k,
    "Entropy": entropy,
    "Global_i_Resistant": global_moransi,
    "Global_i_Sensitive": global_moransi,
    "KL_Divergence": kl_divergence,
    "Local_i_Resistant": local_moransi_dist,
    "Local_i_Sensitive": local_moransi_dist,
    "NN_RS": nn_dist,
    "NN_SR": nn_dist,
    "SES": qcm,
    "Wasserstein": wasserstein,
}

STATISTIC_PARAMS = {
    "in_vitro_pc9": {
        "NC_RS": {"radius": 10, "return_fs": True},
        "NC_SR": {"radius": 10, "return_fs": False},
        "Proportion_Sensitive": {"cell_type": "sensitive"},
        "Spatial_Subsample": {"sample_length": 10},
        "ANNI_RS": {"cell_type1": "resistant", "cell_type2": "sensitive"},
        "ANNI_SR": {"cell_type1": "sensitive", "cell_type2": "resistant"},
        "CPCF_RR": {
            "max_radius": 100,
            "annulus_step": 10,
            "annulus_width": 10,
            "cell_type1": "resistant",
            "cell_type2": "resistant",
        },
        "CPCF_RS": {
            "max_radius": 100,
            "annulus_step": 10,
            "annulus_width": 10,
            "cell_type1": "resistant",
            "cell_type2": "sensitive",
        },
        "CPCF_SR": {
            "max_radius": 100,
            "annulus_step": 10,
            "annulus_width": 10,
            "cell_type1": "sensitive",
            "cell_type2": "resistant",
        },
        "CPCF_SS": {
            "max_radius": 100,
            "annulus_step": 10,
            "annulus_width": 10,
            "cell_type1": "sensitive",
            "cell_type2": "sensitive",
        },
        "Ripleys_k_RR": {
            "max_radius": 100,
            "step": 10,
            "cell_type1": "resistant",
            "cell_type2": "resistant",
        },
        "Ripleys_k_RS": {
            "max_radius": 100,
            "step": 10,
            "cell_type1": "resistant",
            "cell_type2": "sensitive",
        },
        "Ripleys_k_SR": {
            "max_radius": 100,
            "step": 10,
            "cell_type1": "sensitive",
            "cell_type2": "resistant",
        },
        "Ripleys_k_SS": {
            "max_radius": 100,
            "step": 10,
            "cell_type1": "sensitive",
            "cell_type2": "sensitive",
        },
        "Global_Morans_i_Resistant": {"cell_type": "resistant", "side_length": 100},
        "Global_Morans_i_Sensitive": {"cell_type": "sensitive", "side_length": 100},
        "KL_Divergence": {"mesh_step": 100},
        "Local_Morans_i_Resistant": {"cell_type": "resistant", "side_length": 100},
        "Local_Morans_i_Sensitive": {"cell_type": "sensitive", "side_length": 100},
        "NN_RS": {"cell_type1": "resistant", "cell_type2": "sensitive"},
        "NN_SR": {"cell_type1": "sensitive", "cell_type2": "resistant"},
        "SES": {"side_length": 100},
    },
    "in_silico": {
        "NC_RS": {"radius": 3, "return_fs": True},
        "NC_SR": {"radius": 3, "return_fs": False},
        "Proportion_Sensitive": {"cell_type": "sensitive"},
        "Spatial_Subsample": {"sample_length": 5},
        "ANNI_RS": {"cell_type1": "resistant", "cell_type2": "sensitive"},
        "ANNI_SR": {"cell_type1": "sensitive", "cell_type2": "resistant"},
        "CPCF_RR": {
            "max_radius": 10,
            "annulus_step": 2,
            "annulus_width": 2,
            "cell_type1": "resistant",
            "cell_type2": "resistant",
        },
        "CPCF_RS": {
            "max_radius": 10,
            "annulus_step": 2,
            "annulus_width": 2,
            "cell_type1": "resistant",
            "cell_type2": "sensitive",
        },
        "CPCF_SR": {
            "max_radius": 10,
            "annulus_step": 2,
            "annulus_width": 2,
            "cell_type1": "sensitive",
            "cell_type2": "resistant",
        },
        "CPCF_SS": {
            "max_radius": 10,
            "annulus_step": 2,
            "annulus_width": 2,
            "cell_type1": "sensitive",
            "cell_type2": "sensitive",
        },
        "Ripleys_k_RR": {
            "max_radius": 10,
            "step": 2,
            "cell_type1": "resistant",
            "cell_type2": "resistant",
        },
        "Ripleys_k_RS": {
            "max_radius": 10,
            "step": 2,
            "cell_type1": "resistant",
            "cell_type2": "sensitive",
        },
        "Ripleys_k_SR": {
            "max_radius": 10,
            "step": 2,
            "cell_type1": "sensitive",
            "cell_type2": "resistant",
        },
        "Ripleys_k_SS": {
            "max_radius": 10,
            "step": 2,
            "cell_type1": "sensitive",
            "cell_type2": "sensitive",
        },
        "Global_Morans_i_Resistant": {"cell_type": "resistant", "side_length": 10},
        "Global_Morans_i_Sensitive": {"cell_type": "sensitive", "side_length": 10},
        "KL_Divergence": {"mesh_step": 10},
        "Local_Morans_i_Resistant": {"cell_type": "resistant", "side_length": 10},
        "Local_Morans_i_Sensitive": {"cell_type": "sensitive", "side_length": 10},
        "NN_RS": {"cell_type1": "resistant", "cell_type2": "sensitive"},
        "NN_SR": {"cell_type1": "sensitive", "cell_type2": "resistant"},
        "SES": {"side_length": 10},
    },
}
STATISTIC_PARAMS["in_vitro_h358"] = STATISTIC_PARAMS["in_vitro_pc9"]
